import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { escapeHtml, loadConfig } from "../src/core.mjs";

const root = resolve(import.meta.dirname, "..");
const config = await loadConfig(new URL("../one-punch-lp.config.json", import.meta.url));
const fields = config.form.fields.map(renderField).join("\n");
const features = config.site.features.map(([title, body], index) => `<article><span>0${index + 1}</span><h3>${escapeHtml(title)}</h3><p>${escapeHtml(body)}</p></article>`).join("\n");
const publicConfig = JSON.stringify({ project: config.project, endpoint: "__ONE_PUNCH_ENDPOINT__" }).replaceAll("<", "\\u003c");
const html = `<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(config.project.name)}</title><meta name="description" content="${escapeHtml(config.project.description)}"><style>${css()}</style></head>
<body><header><strong>${escapeHtml(config.project.name)}</strong><a href="#contact">相談する</a></header><main><section class="hero"><p class="eyebrow">ONE PUNCH LP / AI INQUIRY FLOW</p><h1>${escapeHtml(config.site.headline)}</h1><p>${escapeHtml(config.site.subheadline)}</p><a class="button" href="#contact">問い合わせを始める →</a></section><section class="features">${features}</section><section id="contact" class="contact"><div><p class="eyebrow">CONTACT</p><h2>相談から、次の仕事まで。</h2><p>入力内容は保存・分類され、通知、タスク化、返信案作成へつながります。</p></div><form id="inquiry-form">${fields}<input class="trap" name="website" tabindex="-1" autocomplete="off"><input type="hidden" name="formStartedAt" id="form-started"><button type="submit">送信する</button><p id="status" role="status"></p></form></section></main><footer><span>${escapeHtml(config.project.name)}</span><span>Fictional demo / source-owned automation</span></footer><script>window.ONE_PUNCH=${publicConfig};${browserJs()}</script></body></html>`;
await mkdir(resolve(root, "dist"), { recursive: true });
await writeFile(resolve(root, "dist/index.html"), html, "utf8");
console.log("Generated dist/index.html");

function renderField(field) {
  const attrs = `name="${escapeHtml(field.id)}" id="${escapeHtml(field.id)}" ${field.required ? "required" : ""} maxlength="${field.maxLength ?? 1000}"`;
  const label = `<label for="${escapeHtml(field.id)}">${escapeHtml(field.label)}${field.required ? " *" : ""}</label>`;
  if (field.type === "textarea") return `<div class="field wide">${label}<textarea ${attrs} rows="6"></textarea></div>`;
  if (field.type === "select") return `<div class="field">${label}<select ${attrs}><option value="">選択してください</option>${field.options.map((v) => `<option>${escapeHtml(v)}</option>`).join("")}</select></div>`;
  return `<div class="field">${label}<input type="${escapeHtml(field.type)}" ${attrs}></div>`;
}
function browserJs() { return `
const form=document.querySelector('#inquiry-form'),status=document.querySelector('#status'),started=document.querySelector('#form-started');started.value=Date.now();
form.addEventListener('submit',async(e)=>{e.preventDefault();status.textContent='送信しています…';const payload=Object.fromEntries(new FormData(form));payload._pageUrl=location.href;payload._userAgent=navigator.userAgent;const endpoint=window.ONE_PUNCH.endpoint==='__ONE_PUNCH_ENDPOINT__'?'/api/inquiries':window.ONE_PUNCH.endpoint;try{const response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.message||'送信できませんでした');form.reset();started.value=Date.now();status.textContent='お問い合わせを受け付けました。';}catch(error){status.textContent=error.message;}});` }
function css() { return `:root{--ink:#111827;--paper:#f5f2ea;--line:#d9d4c8;--accent:#ff5a36}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font-family:Inter,"Noto Sans JP",sans-serif}header,main,footer{max-width:1180px;margin:auto;padding-left:28px;padding-right:28px}header{height:78px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line)}header a,.button{color:inherit;text-decoration:none;border-bottom:2px solid var(--ink)}.hero{padding:100px 0 82px}.eyebrow{font:700 12px ui-monospace;letter-spacing:.15em;color:#636b78}.hero h1{max-width:950px;margin:18px 0;font-family:Georgia,"Noto Serif JP",serif;font-size:clamp(52px,9vw,112px);line-height:.94;letter-spacing:-.055em}.hero>p:not(.eyebrow){max-width:620px;font-size:20px;line-height:1.8;color:#4b5563}.button{display:inline-block;margin-top:20px;padding:14px 0;font-weight:700}.features{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--line);border-bottom:1px solid var(--line)}article{padding:36px 24px;min-height:240px;border-right:1px solid var(--line)}article:last-child{border:0}article span{font:700 12px ui-monospace;color:var(--accent)}article h3{font-size:28px;margin:54px 0 12px}article p{line-height:1.8;color:#5d6470}.contact{display:grid;grid-template-columns:.8fr 1.2fr;gap:64px;padding:100px 0}.contact h2{font-family:Georgia,"Noto Serif JP",serif;font-size:52px;line-height:1.05}form{display:grid;grid-template-columns:1fr 1fr;gap:20px;background:white;padding:34px;border:1px solid var(--line);box-shadow:10px 10px 0 var(--ink)}.field{display:grid;gap:8px}.wide,form button,#status{grid-column:1/-1}label{font-size:13px;font-weight:700}input,select,textarea{width:100%;font:inherit;padding:13px;border:1px solid #bbb;background:#fff}textarea{resize:vertical}form button{padding:16px;border:0;background:var(--ink);color:white;font-weight:800;cursor:pointer}.trap{position:absolute;left:-9999px}#status{min-height:20px;margin:0;color:#4b5563}footer{display:flex;justify-content:space-between;padding-top:28px;padding-bottom:48px;border-top:1px solid var(--line);font-size:13px;color:#6b7280}@media(max-width:760px){.features,.contact{grid-template-columns:1fr}article{border-right:0;border-bottom:1px solid var(--line)}form{grid-template-columns:1fr}.field{grid-column:1/-1}.hero{padding-top:60px}.contact h2{font-size:40px}}`; }
